# Generated by Django 5.2.8 on 2025-11-22 12:12

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("course", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="info",
            name="place_of_origin",
            field=models.CharField(default="kathmandu", max_length=100),
            preserve_default=False,
        ),
    ]
