# Generated by Django 5.2.8 on 2025-11-22 12:15

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("course", "0002_info_place_of_origin"),
    ]

    operations = [
        migrations.AddField(
            model_name="info",
            name="email",
            field=models.EmailField(default="abinaya13@gmail.com", max_length=100),
        ),
    ]
