# Generated by Django 5.2.8 on 2025-11-28 09:42

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("student", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="group",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("group_name", models.CharField(max_length=100)),
                ("group_rank", models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name="marks",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("stu_sub", models.CharField(max_length=50)),
                ("marks", models.IntegerField()),
            ],
        ),
    ]
