# Generated by Django 5.2.8 on 2025-11-22 17:34

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("student", "0001_initial"),
    ]

    operations = [
        migrations.RenameModel(
            old_name="info",
            new_name="profile",
        ),
    ]
